---
- hosts: mywebservers
  become: yes
  tasks:
  - name: in this tasks , i want install java on ubuntu
    apt:
      name: "{{myjavaonubuntu}}"
      state: present
    when: ansible_os_family== "Debian"

  - name: in this tasks, i want install java on RedHat 
    dnf:
      name: "{{myjavaonredhat}}"
      state: present
    when: ansible_os_family== "RedHat" 