---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: in this tasks , i want install apache2 webservers on ubuntu
    apt: 
      name: apache2
      state: present
  - name: in this tasks, i want to start apache2 webservers on ubuntu
    service:
      name: apache2
      state: started