---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: in this tasks , i want install apache2 webservers on ubuntu
    apt: 
      name: "{{mywebpackonubuntu}}"
      state: present
    when: ansible_os_family== "Debian"
  - name: in this tasks, i want to start apache2 webservers on ubuntu
    service:
      name: "{{mywebpackonubuntu}}"
      state: started
    when: ansible_os_family== "Debian"
  - name: in this tasks, i want install httpd webservers on RedHat
    dnf:
      name: "{{mywebpackonredhat}}"
      state: present
    when: ansible_os_family== "RedHat"
  - name: in this tasks, i want to webservers on RedHat
    service:
      name: "{{mywebpackonredhat}}"
      state: started
    when: ansible_os_family== "RedHat"